services:
  mysql:
    image: mysql:8.0
    container_name: automex_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: automex
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - automex_network

  backend:
    image: procoder9937/automex:backend
    container_name: automex_backend
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://root:root@mysql:3306/automex
      - HOST=0.0.0.0
      - PORT=8000
      - PORT=8000
      - DEBUG=False
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - automex_network

  frontend:
    image: procoder9937/automex:frontend
    container_name: automex_frontend
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - VITE_API_URL=/api/v1
    depends_on:
      - backend
    networks:
      - automex_network

  nginx:
    image: procoder9937/automex:nginx
    container_name: automex_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - automex_network
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mysql_data:
    driver: local

networks:
  automex_network:
    driver: bridge
