import { create } from "zustand";

export type FuelType = "Petrol" | "Diesel" | "CNG" | "Hybrid" | "Electric";

export interface CarModel {
  id: string;
  name: string;
  fuelTypes: FuelType[];
}

export interface CarBrand {
  id: string;
  name: string;
  logo: string;
  models: CarModel[];
}

const carCatalog: CarBrand[] = [
  {
    id: "audi",
    name: "Audi",
    logo: "/images/car_brands/Audi.png",
    models: [
      { id: "audi-a3", name: "A3", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-a4", name: "A4", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-a5", name: "A5", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-a6", name: "A6", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-a7", name: "A7", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-a8", name: "A8", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-a8-l", name: "A8 L", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-q2", name: "Q2", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-q3", name: "Q3", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-q3-sportback", name: "Q3 Sportback", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-q5", name: "Q5", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-q7", name: "Q7", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-q8", name: "Q8", fuelTypes: ["Petrol", "Diesel"] },
      { id: "audi-s4", name: "S4", fuelTypes: ["Petrol"] },
      { id: "audi-tt", name: "TT", fuelTypes: ["Petrol"] },
      { id: "audi-r8", name: "R8", fuelTypes: ["Petrol"] },
      { id: "audi-rs3", name: "RS3", fuelTypes: ["Petrol"] },
      { id: "audi-rs5", name: "RS5", fuelTypes: ["Petrol"] },
      { id: "audi-rs-q8", name: "RS Q8", fuelTypes: ["Petrol"] },
      { id: "audi-e-tron", name: "Q8 e-tron", fuelTypes: ["Electric"] },
      { id: "audi-q8-sportback-e-tron", name: "Q8 Sportback e-tron", fuelTypes: ["Electric"] },
      { id: "audi-e-tron-gt", name: "E-tron GT", fuelTypes: ["Electric"] },
      { id: "audi-rs-e-tron-gt", name: "RS e-tron GT", fuelTypes: ["Electric"] },
    ],
  },
  {
    id: "bmw",
    name: "BMW",
    logo: "/images/car_brands/BMW.png",
    models: [
      { id: "bmw-1-series", name: "1 Series", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-2-series", name: "2 Series", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-3-series", name: "3 Series", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-3-series-gt", name: "3 Series GT", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-5-series", name: "5 Series", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-5-series-gt", name: "5 Series GT", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-6-series", name: "6 Series", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-6-series-gt", name: "6 Series GT", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-7-series", name: "7 Series", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-x1", name: "X1", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-x3", name: "X3", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-x4", name: "X4", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-x4-m40i", name: "X4 M40i", fuelTypes: ["Petrol"] },
      { id: "bmw-x5", name: "X5", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-x5-m-competition", name: "X5 M Competition", fuelTypes: ["Petrol"] },
      { id: "bmw-x6", name: "X6", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-x7", name: "X7", fuelTypes: ["Petrol", "Diesel"] },
      { id: "bmw-xm", name: "XM", fuelTypes: ["Hybrid"] },
      { id: "bmw-z4", name: "Z4", fuelTypes: ["Petrol"] },
      { id: "bmw-m2", name: "M2", fuelTypes: ["Petrol"] },
      { id: "bmw-m3", name: "M3", fuelTypes: ["Petrol"] },
      { id: "bmw-m340i", name: "M340i", fuelTypes: ["Petrol"] },
      { id: "bmw-m5", name: "M5", fuelTypes: ["Petrol"] },
      { id: "bmw-i4", name: "i4", fuelTypes: ["Electric"] },
      { id: "bmw-i7", name: "i7", fuelTypes: ["Electric"] },
      { id: "bmw-ix", name: "iX", fuelTypes: ["Electric"] },
    ],
  },
  {
    id: "mercedes",
    name: "Mercedes-Benz",
    logo: "/images/car_brands/mercidiescarlogo.png",
    models: [
      { id: "mercedes-a-class", name: "A-Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-a-180", name: "A 180", fuelTypes: ["Petrol"] },
      { id: "mercedes-a-180-d", name: "A 180 d", fuelTypes: ["Diesel"] },
      { id: "mercedes-a-200", name: "A 200", fuelTypes: ["Petrol"] },
      { id: "mercedes-a-200-d", name: "A 200 d", fuelTypes: ["Diesel"] },
      { id: "mercedes-a-220", name: "A 220", fuelTypes: ["Petrol"] },
      { id: "mercedes-a-250", name: "A 250", fuelTypes: ["Petrol"] },
      { id: "mercedes-amg-a-45-s", name: "AMG A 45 S", fuelTypes: ["Petrol"] },
      { id: "mercedes-b-class", name: "B-Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-c-class", name: "C-Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-amg-c-43", name: "AMG C 43", fuelTypes: ["Petrol"] },
      { id: "mercedes-cla-class", name: "CLA Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-cls-class", name: "CLS Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-e-class", name: "E-Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-r-class", name: "R Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-s-class", name: "S-Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-maybach-s-class", name: "Maybach S-Class", fuelTypes: ["Petrol"] },
      { id: "mercedes-v-class", name: "V-Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-gla", name: "GLA Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-amg-gla-35", name: "AMG GLA 35", fuelTypes: ["Petrol"] },
      { id: "mercedes-glb", name: "GLB", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-glc", name: "GLC", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-amg-glc-43", name: "AMG GLC 43", fuelTypes: ["Petrol"] },
      { id: "mercedes-gle", name: "GLE 250d", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-gle43-amg", name: "GLE43 AMG", fuelTypes: ["Petrol"] },
      { id: "mercedes-amg-gle-53", name: "AMG GLE 53", fuelTypes: ["Petrol"] },
      { id: "mercedes-gl-class", name: "GL Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-gls", name: "GLS", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-amg-gls-63", name: "AMG GLS 63", fuelTypes: ["Petrol"] },
      { id: "mercedes-maybach-gls", name: "Maybach GLS", fuelTypes: ["Petrol"] },
      { id: "mercedes-ml-class", name: "ML Class", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mercedes-g-400-d", name: "G 400 d", fuelTypes: ["Diesel"] },
      { id: "mercedes-g63-amg", name: "G63 AMG", fuelTypes: ["Petrol"] },
      { id: "mercedes-slk-class", name: "SLK Class", fuelTypes: ["Petrol"] },
      { id: "mercedes-sl-500-amg", name: "SL 500 AMG", fuelTypes: ["Petrol"] },
      { id: "mercedes-amg-gt", name: "AMG GT", fuelTypes: ["Petrol"] },
      { id: "mercedes-eqa", name: "EQA", fuelTypes: ["Electric"] },
      { id: "mercedes-eqb", name: "EQB", fuelTypes: ["Electric"] },
      { id: "mercedes-eqc", name: "EQC", fuelTypes: ["Electric"] },
      { id: "mercedes-eqe-sedan", name: "EQE Sedan", fuelTypes: ["Electric"] },
      { id: "mercedes-eqs", name: "EQS", fuelTypes: ["Electric"] },
      { id: "mercedes-eqs-suv", name: "EQS SUV", fuelTypes: ["Electric"] },
    ],
  },
  {
    id: "skoda",
    name: "Skoda",
    logo: "/images/car_brands/Skoda.png",
    models: [
      { id: "skoda-rapid", name: "Rapid", fuelTypes: ["Petrol", "Diesel"] },
      { id: "skoda-fabia", name: "Fabia", fuelTypes: ["Petrol", "Diesel"] },
      { id: "skoda-superb", name: "Superb", fuelTypes: ["Petrol", "Diesel"] },
      { id: "skoda-laura", name: "Laura", fuelTypes: ["Petrol", "Diesel"] },
      { id: "skoda-octavia", name: "Octavia", fuelTypes: ["Petrol", "Diesel"] },
      { id: "skoda-yeti", name: "Yeti", fuelTypes: ["Petrol", "Diesel"] },
      { id: "skoda-kodiaq", name: "Kodiaq", fuelTypes: ["Petrol", "Diesel"] },
      { id: "skoda-kushaq", name: "Kushaq", fuelTypes: ["Petrol"] },
      { id: "skoda-kylaq", name: "Kylaq", fuelTypes: ["Petrol"] },
      { id: "skoda-slavia", name: "Slavia", fuelTypes: ["Petrol"] },
    ],
  },
  {
    id: "jaguar",
    name: "Jaguar",
    logo: "/images/car_brands/jaguarcarlogo.png",
    models: [
      { id: "jaguar-xe", name: "XE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "jaguar-xf", name: "XF", fuelTypes: ["Petrol", "Diesel"] },
      { id: "jaguar-xj", name: "XJ", fuelTypes: ["Petrol", "Diesel"] },
      { id: "jaguar-xjr", name: "XJR", fuelTypes: ["Petrol"] },
      { id: "jaguar-xk-r", name: "XK R", fuelTypes: ["Petrol"] },
      { id: "jaguar-e-pace", name: "E-PACE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "jaguar-i-pace", name: "I-PACE", fuelTypes: ["Electric"] },
      { id: "jaguar-i-pace-black", name: "I-PACE Black", fuelTypes: ["Electric"] },
      { id: "jaguar-i-pace-hse", name: "I-PACE HSE", fuelTypes: ["Electric"] },
      { id: "jaguar-i-pace-se", name: "I-PACE SE", fuelTypes: ["Electric"] },
      { id: "jaguar-f-type", name: "F-TYPE", fuelTypes: ["Petrol"] },
      { id: "jaguar-f-type-r-coupe", name: "F-TYPE R Coupe", fuelTypes: ["Petrol"] },
      { id: "jaguar-f-pace-svr", name: "F-PACE SVR", fuelTypes: ["Petrol"] },
      { id: "jaguar-r-dynamic-black", name: "R-Dynamic Black", fuelTypes: ["Petrol", "Diesel"] },
      { id: "jaguar-r-dynamic-coupe", name: "R-Dynamic Coupe", fuelTypes: ["Petrol"] },
      { id: "jaguar-r-dynamic-s", name: "R-Dynamic S", fuelTypes: ["Petrol", "Diesel"] },
      { id: "jaguar-r-dynamic-se", name: "R-Dynamic SE", fuelTypes: ["Petrol", "Diesel"] },
    ],
  },
  {
    id: "volkswagen",
    name: "Volkswagen",
    logo: "/images/car_brands/volkswagancarlogo.png",
    models: [
      { id: "vw-polo", name: "Polo", fuelTypes: ["Petrol", "Diesel"] },
      { id: "vw-vento", name: "Vento", fuelTypes: ["Petrol", "Diesel"] },
      { id: "vw-ameo", name: "Ameo", fuelTypes: ["Petrol", "Diesel"] },
      { id: "vw-cross-polo", name: "Cross Polo", fuelTypes: ["Petrol", "Diesel"] },
      { id: "vw-jetta", name: "Jetta", fuelTypes: ["Petrol", "Diesel"] },
      { id: "vw-passat", name: "Passat", fuelTypes: ["Petrol", "Diesel"] },
      { id: "vw-taigun", name: "Taigun", fuelTypes: ["Petrol"] },
      { id: "vw-t-roc", name: "T-Roc", fuelTypes: ["Petrol"] },
      { id: "vw-tiguan", name: "Tiguan", fuelTypes: ["Petrol"] },
      { id: "vw-beetle", name: "Beetle", fuelTypes: ["Petrol", "Diesel"] },
      { id: "vw-virtus", name: "Virtus", fuelTypes: ["Petrol"] },
      { id: "vw-phaeton", name: "Phaeton", fuelTypes: ["Petrol", "Diesel"] },
    ],
  },
  {
    id: "maruti-suzuki",
    name: "Maruti Suzuki",
    logo: "/images/car_brands/suzukicarlogo.png",
    models: [
      { id: "maruti-800", name: "800", fuelTypes: ["Petrol"] },
      { id: "maruti-alto", name: "Alto", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-alto-800", name: "Alto 800", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-alto-k10", name: "Alto K10", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-zen", name: "Zen", fuelTypes: ["Petrol"] },
      { id: "maruti-a-star", name: "A-Star", fuelTypes: ["Petrol"] },
      { id: "maruti-swift", name: "Swift", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-swift-dzire", name: "Swift Dzire", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { id: "maruti-wagon-r", name: "WagonR", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-ritz", name: "Ritz", fuelTypes: ["Petrol", "Diesel"] },
      { id: "maruti-celerio", name: "Celerio", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-ignis", name: "Ignis", fuelTypes: ["Petrol"] },
      { id: "maruti-baleno", name: "Baleno", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-ciaz", name: "Ciaz", fuelTypes: ["Petrol", "Diesel"] },
      { id: "maruti-kizashi", name: "Kizashi", fuelTypes: ["Petrol"] },
      { id: "maruti-esteem", name: "Esteem", fuelTypes: ["Petrol"] },
      { id: "maruti-estilo", name: "Estilo", fuelTypes: ["Petrol"] },
      { id: "maruti-sx4", name: "SX4", fuelTypes: ["Petrol", "Diesel"] },
      { id: "maruti-s-cross", name: "S-Cross", fuelTypes: ["Petrol", "Diesel"] },
      { id: "maruti-gypsy", name: "Gypsy", fuelTypes: ["Petrol"] },
      { id: "maruti-omni", name: "Omni", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-eeco", name: "Eeco", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-versa", name: "Versa", fuelTypes: ["Petrol", "Diesel"] },
      { id: "maruti-ertiga", name: "Ertiga", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { id: "maruti-xl6", name: "XL6", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-s-presso", name: "S-Presso", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-fronx", name: "Fronx", fuelTypes: ["Petrol", "CNG"] },
      { id: "maruti-jimny", name: "Jimny", fuelTypes: ["Petrol"] },
      { id: "maruti-vitara-brezza", name: "Vitara Brezza", fuelTypes: ["Petrol", "Diesel"] },
      { id: "maruti-vitara", name: "Grand Vitara", fuelTypes: ["Petrol", "Hybrid"] },
      { id: "maruti-new-grand-vitara", name: "New Grand Vitara", fuelTypes: ["Petrol", "Hybrid"] },
      { id: "maruti-invicto", name: "Invicto", fuelTypes: ["Hybrid"] },
    ],
  },
  {
    id: "mahindra",
    name: "Mahindra",
    logo: "/images/car_brands/Mahindracarlogo.png",
    models: [
      { id: "mahindra-xuv700", name: "XUV700", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mahindra-xuv500", name: "XUV 500", fuelTypes: ["Diesel"] },
      { id: "mahindra-xuv3xo", name: "XUV 3XO", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mahindra-xuv300", name: "XUV300", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mahindra-xuv400", name: "XUV400", fuelTypes: ["Electric"] },
      { id: "mahindra-xev9e", name: "XEV 9e", fuelTypes: ["Electric"] },
      { id: "mahindra-be6", name: "BE 6", fuelTypes: ["Electric"] },
      { id: "mahindra-scorpio", name: "Scorpio", fuelTypes: ["Diesel"] },
      { id: "mahindra-scorpio-n", name: "Scorpio N", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mahindra-scorpio-getaway", name: "Scorpio Getaway", fuelTypes: ["Diesel"] },
      { id: "mahindra-alturas-g4", name: "Alturas G4", fuelTypes: ["Diesel"] },
      { id: "mahindra-kuv100", name: "KUV 100", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mahindra-thar", name: "Thar", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mahindra-thar-roxx", name: "Thar Roxx", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mahindra-logan", name: "Logan", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mahindra-verito", name: "Verito", fuelTypes: ["Diesel"] },
      { id: "mahindra-verito-vibe-cs", name: "Verito Vibe CS", fuelTypes: ["Diesel"] },
      { id: "mahindra-nuvosport", name: "NuvoSport", fuelTypes: ["Diesel"] },
      { id: "mahindra-xylo", name: "Xylo", fuelTypes: ["Diesel"] },
      { id: "mahindra-marazzo", name: "Marazzo", fuelTypes: ["Diesel"] },
      { id: "mahindra-tuv300", name: "TUV 300", fuelTypes: ["Diesel"] },
      { id: "mahindra-tuv300-plus", name: "TUV 300 Plus", fuelTypes: ["Diesel"] },
      { id: "mahindra-bolero-neo", name: "Bolero Neo", fuelTypes: ["Diesel"] },
      { id: "mahindra-bolero", name: "Bolero", fuelTypes: ["Diesel"] },
      { id: "mahindra-bolero-camper", name: "Bolero Camper", fuelTypes: ["Diesel"] },
      { id: "mahindra-bolero-pickup", name: "Bolero Pickup", fuelTypes: ["Diesel"] },
      { id: "mahindra-e20-plus", name: "E20 Plus", fuelTypes: ["Electric"] },
      { id: "mahindra-reva", name: "Reva", fuelTypes: ["Electric"] },
      { id: "mahindra-quanto", name: "Quanto", fuelTypes: ["Diesel"] },
      { id: "mahindra-imperio", name: "Imperio", fuelTypes: ["Diesel"] },
    ],
  },
  {
    id: "volvo",
    name: "Volvo",
    logo: "/images/car_brands/Volvo.png",
    models: [
      { id: "volvo-s60", name: "S60", fuelTypes: ["Petrol", "Hybrid"] },
      { id: "volvo-s80", name: "S80", fuelTypes: ["Petrol", "Diesel"] },
      { id: "volvo-s90", name: "S90", fuelTypes: ["Petrol", "Diesel", "Hybrid"] },
      { id: "volvo-s40", name: "S40", fuelTypes: ["Petrol", "Diesel"] },
      { id: "volvo-s60-cross-country", name: "S60 Cross Country", fuelTypes: ["Petrol", "Diesel"] },
      { id: "volvo-v40", name: "V40", fuelTypes: ["Petrol", "Diesel"] },
      { id: "volvo-v60", name: "V60", fuelTypes: ["Petrol", "Diesel", "Hybrid"] },
      { id: "volvo-v90", name: "V90", fuelTypes: ["Petrol", "Diesel", "Hybrid"] },
      { id: "volvo-v40-cross-country", name: "V40 Cross Country", fuelTypes: ["Petrol", "Diesel"] },
      { id: "volvo-xc40", name: "XC 40", fuelTypes: ["Petrol", "Electric"] },
      { id: "volvo-xc60", name: "XC60", fuelTypes: ["Petrol", "Diesel", "Hybrid"] },
      { id: "volvo-xc90", name: "XC90", fuelTypes: ["Petrol", "Diesel", "Hybrid"] },
    ],
  },
  {
    id: "land-rover",
    name: "Land Rover",
    logo: "/images/car_brands/Land Rover.png",
    models: [
      { id: "landrover-range-rover-sport", name: "Range Rover Sport", fuelTypes: ["Petrol", "Diesel", "Hybrid"] },
      { id: "landrover-range-rover-sport-se", name: "Range Rover Sport – SE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-sport-hse", name: "Range Rover Sport – HSE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-sport-dynamic-se", name: "Range Rover Sport – Dynamic SE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-sport-dynamic-hse", name: "Range Rover Sport – Dynamic HSE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-sport-autobiography", name: "Range Rover Sport – Autobiography", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-sport-sv", name: "Range Rover Sport – SV", fuelTypes: ["Petrol"] },
      { id: "landrover-range-rover-evoque", name: "Range Rover Evoque", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-evoque-dynamic-se", name: "Range Rover Evoque – Dynamic SE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-vogue", name: "Range Rover Vogue", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-autobiography", name: "Range Rover – Autobiography", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-sv", name: "Range Rover – SV", fuelTypes: ["Petrol"] },
      { id: "landrover-range-rover-velar-dynamic-se", name: "Range Rover Velar – Dynamic SE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-range-rover-velar-dynamic-hse", name: "Range Rover Velar – Dynamic HSE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-discovery-sport-dynamic-se", name: "Discovery Sport – Dynamic SE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-defender-90-x-dynamic-hse", name: "Defender 90 – X-Dynamic HSE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-defender-110-se", name: "Defender 110 – SE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-defender-110-hse", name: "Defender 110 – HSE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-defender-110-x-dynamic-hse", name: "Defender 110 – X-Dynamic HSE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-defender-110-v8", name: "Defender 110 – V8", fuelTypes: ["Petrol"] },
      { id: "landrover-defender-130-se", name: "Defender 130 – SE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-defender-130-hse", name: "Defender 130 – HSE", fuelTypes: ["Petrol", "Diesel"] },
      { id: "landrover-freelander-2", name: "Freelander 2", fuelTypes: ["Petrol", "Diesel"] },
    ],
  },
  {
    id: "toyota",
    name: "Toyota",
    logo: "/images/car_brands/toyotacarlogo.png",
    models: [
      { id: "toyota-fortuner", name: "Fortuner", fuelTypes: ["Petrol", "Diesel"] },
      { id: "toyota-hilux", name: "Hilux", fuelTypes: ["Diesel"] },
      { id: "toyota-land-cruiser", name: "Land Cruiser", fuelTypes: ["Petrol", "Diesel"] },
      { id: "toyota-land-cruiser-prado", name: "Land Cruiser Prado", fuelTypes: ["Diesel"] },
      { id: "toyota-urban-cruiser", name: "Urban Cruiser", fuelTypes: ["Petrol"] },
      { id: "toyota-urban-cruiser-hyryder", name: "Urban Cruiser Hyryder", fuelTypes: ["Petrol", "Hybrid", "CNG"] },
      { id: "toyota-innova", name: "Innova", fuelTypes: ["Petrol", "Diesel"] },
      { id: "toyota-innova-crysta", name: "Innova Crysta", fuelTypes: ["Petrol", "Diesel"] },
      { id: "toyota-innova-hycross", name: "Innova Hycross", fuelTypes: ["Hybrid"] },
      { id: "toyota-hycross", name: "HyCross", fuelTypes: ["Hybrid"] },
      { id: "toyota-qualis", name: "Qualis", fuelTypes: ["Diesel"] },
      { id: "toyota-alphard", name: "Alphard", fuelTypes: ["Petrol", "Hybrid"] },
      { id: "toyota-vellfire", name: "Vellfire", fuelTypes: ["Petrol", "Hybrid"] },
      { id: "toyota-camry", name: "Camry", fuelTypes: ["Petrol", "Hybrid"] },
      { id: "toyota-corolla", name: "Corolla", fuelTypes: ["Petrol", "Diesel"] },
      { id: "toyota-corolla-altis", name: "Corolla Altis", fuelTypes: ["Petrol", "Diesel", "Hybrid"] },
      { id: "toyota-etios", name: "Etios", fuelTypes: ["Petrol", "Diesel"] },
      { id: "toyota-etios-cross", name: "Etios Cross", fuelTypes: ["Petrol", "Diesel"] },
      { id: "toyota-etios-liva", name: "Etios Liva", fuelTypes: ["Petrol", "Diesel"] },
      { id: "toyota-yaris", name: "Yaris", fuelTypes: ["Petrol"] },
      { id: "toyota-glanza", name: "Glanza", fuelTypes: ["Petrol", "CNG"] },
    ],
  },
  {
    id: "kia",
    name: "Kia",
    logo: "/images/car_brands/kiacarlogo.png",
    models: [
      { id: "kia-seltos", name: "Seltos", fuelTypes: ["Petrol", "Diesel"] },
      { id: "kia-sonet", name: "Sonet", fuelTypes: ["Petrol", "Diesel"] },
      { id: "kia-syros", name: "Syros", fuelTypes: ["Petrol", "Diesel"] },
      { id: "kia-carens", name: "Carens", fuelTypes: ["Petrol", "Diesel"] },
      { id: "kia-carnival", name: "Carnival", fuelTypes: ["Diesel"] },
      { id: "kia-ev6", name: "EV6", fuelTypes: ["Electric"] },
    ],
  },
  {
    id: "mg",
    name: "MG",
    logo: "/images/car_brands/mgcarlogo.png",
    models: [
      { id: "mg-hector", name: "Hector", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mg-hector-plus", name: "Hector Plus", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mg-gloster", name: "Gloster", fuelTypes: ["Diesel"] },
      { id: "mg-astor", name: "Astor", fuelTypes: ["Petrol"] },
      { id: "mg-zsev", name: "ZS EV", fuelTypes: ["Electric"] },
      { id: "mg-windsor", name: "Windsor", fuelTypes: ["Electric"] },
      { id: "mg-comet", name: "Comet", fuelTypes: ["Electric"] },
    ],
  },
  {
    id: "mini",
    name: "Mini",
    logo: "/images/car_brands/minicarlogo.png",
    models: [
      { id: "mini-cooper", name: "Cooper", fuelTypes: ["Petrol"] },
      { id: "mini-cooper-s", name: "Cooper S", fuelTypes: ["Petrol"] },
      { id: "mini-cooper-se", name: "Cooper SE", fuelTypes: ["Electric"] },
      { id: "mini-countryman", name: "Countryman", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mini-clubman", name: "Clubman", fuelTypes: ["Petrol", "Diesel"] },
      { id: "mini-electric", name: "Electric", fuelTypes: ["Electric"] },
    ],
  },
  {
    id: "lexus",
    name: "Lexus",
    logo: "/images/car_brands/lexuscarlogo.png",
    models: [
      { id: "lexus-es", name: "ES", fuelTypes: ["Hybrid"] },
      { id: "lexus-ls", name: "LS", fuelTypes: ["Petrol", "Hybrid"] },
      { id: "lexus-nx", name: "NX", fuelTypes: ["Hybrid"] },
      { id: "lexus-rx", name: "RX", fuelTypes: ["Petrol", "Hybrid"] },
      { id: "lexus-lx", name: "LX", fuelTypes: ["Petrol"] },
      { id: "lexus-lc", name: "LC", fuelTypes: ["Petrol", "Hybrid"] },
      { id: "lexus-ux", name: "UX", fuelTypes: ["Electric"] },
    ],
  },
  {
    id: "hyundai",
    name: "Hyundai",
    logo: "/images/car_brands/hundaicarlogo.png",
    models: [
      { id: "hyundai-i10", name: "i10", fuelTypes: ["Petrol", "CNG"] },
      { id: "hyundai-i20", name: "i20", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-grand-i10", name: "Grand i10", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { id: "hyundai-grand-i10-nios", name: "Grand i10 Nios", fuelTypes: ["Petrol", "CNG"] },
      { id: "hyundai-santro", name: "Santro", fuelTypes: ["Petrol", "CNG"] },
      { id: "hyundai-santro-xing", name: "Santro Xing", fuelTypes: ["Petrol", "CNG"] },
      { id: "hyundai-eon", name: "Eon", fuelTypes: ["Petrol"] },
      { id: "hyundai-getz", name: "Getz", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-getz-prime", name: "Getz Prime", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-xcent", name: "Xcent", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-accent", name: "Accent", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-accent-viva", name: "Accent Viva", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-aura", name: "Aura", fuelTypes: ["Petrol", "Diesel", "CNG"] },
      { id: "hyundai-elite-i20", name: "Elite i20", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-i20-active", name: "i20 Active", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-i20-n-line", name: "i20 N Line", fuelTypes: ["Petrol"] },
      { id: "hyundai-verna", name: "Verna", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-verna-fluidic", name: "Verna Fluidic", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-verna-transform", name: "Verna Transform", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-elantra", name: "Elantra", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-sonata", name: "Sonata", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-sonata-embera", name: "Sonata Embera", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-sonata-transform", name: "Sonata Transform", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-creta", name: "Creta", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-alcazar", name: "Alcazar", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-venue", name: "Venue", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-venue-n-line", name: "Venue N Line", fuelTypes: ["Petrol"] },
      { id: "hyundai-exter", name: "Exter", fuelTypes: ["Petrol", "CNG"] },
      { id: "hyundai-kona", name: "Kona", fuelTypes: ["Electric"] },
      { id: "hyundai-tucson", name: "Tucson", fuelTypes: ["Petrol", "Diesel"] },
      { id: "hyundai-santa-fe", name: "SantaFE", fuelTypes: ["Diesel"] },
    ],
  },
  {
    id: "jeep",
    name: "Jeep",
    logo: "/images/car_brands/jeepcarlogo.png",
    models: [
      { id: "jeep-compass", name: "Compass", fuelTypes: ["Petrol", "Diesel"] },
      { id: "jeep-wrangler", name: "Wrangler", fuelTypes: ["Petrol", "Diesel"] },
      { id: "jeep-grand-cherokee", name: "Grand Cherokee", fuelTypes: ["Petrol", "Diesel"] },
      { id: "jeep-meridian", name: "Meridian", fuelTypes: ["Diesel"] },
    ],
  },
  {
    id: "nissan",
    name: "Nissan",
    logo: "/images/car_brands/nissancarlogo.png",
    models: [
      { id: "nissan-magnite", name: "Magnite", fuelTypes: ["Petrol"] },
      { id: "nissan-kicks", name: "Kicks", fuelTypes: ["Petrol", "Diesel"] },
      { id: "nissan-terrano", name: "Terrano", fuelTypes: ["Petrol", "Diesel"] },
      { id: "nissan-x-trail", name: "X-Trail", fuelTypes: ["Petrol", "Diesel"] },
      { id: "nissan-micra", name: "Micra", fuelTypes: ["Petrol", "Diesel"] },
      { id: "nissan-micra-active", name: "Micra Active", fuelTypes: ["Petrol", "Diesel"] },
      { id: "nissan-sunny", name: "Sunny", fuelTypes: ["Petrol", "Diesel"] },
      { id: "nissan-teana", name: "Teana", fuelTypes: ["Petrol"] },
      { id: "nissan-evalia", name: "Evalia", fuelTypes: ["Diesel"] },
      { id: "nissan-gtr", name: "GTR", fuelTypes: ["Petrol"] },
      { id: "nissan-leaf", name: "Leaf", fuelTypes: ["Electric"] },
    ],
  },
];

interface CarSelectionState {
  catalog: CarBrand[];
  selectedBrandId?: string;
  selectedModelId?: string;
  selectedFuelType?: FuelType;
  selectedPart?: string; // Service/Part name being booked
  selectedDate?: Date; // Selected booking date
  highlightTrigger: boolean; // Flag to trigger highlight animation
  selectBrand: (brandId: string) => void;
  selectModel: (modelId: string) => void;
  selectFuelType: (fuel: FuelType) => void;
  selectPart: (part: string) => void;
  selectDate: (date: Date) => void;
  clearBrand: () => void;
  clearModel: () => void;
  resetSelection: () => void;
  isCarSelected: () => boolean; // Helper to check if brand, model, and fuel are all selected
  triggerHighlight: () => void; // Trigger highlight animation
  clearHighlight: () => void; // Clear highlight animation
}

export const useCarSelectionStore = create<CarSelectionState>()((set, get) => ({
  catalog: carCatalog,
  selectedBrandId: undefined,
  selectedModelId: undefined,
  selectedFuelType: undefined,
  selectedPart: undefined,
  selectedDate: undefined,
  highlightTrigger: false,
  selectBrand: (brandId) =>
    set({
      selectedBrandId: brandId,
      selectedModelId: undefined,
      selectedFuelType: undefined,
      highlightTrigger: false, // Clear highlight when user makes a selection
    }),
  selectModel: (modelId) =>
    set({
      selectedModelId: modelId,
      selectedFuelType: undefined,
      highlightTrigger: false, // Clear highlight when user makes a selection
    }),
  selectFuelType: (fuel) =>
    set({
      selectedFuelType: fuel,
      highlightTrigger: false, // Clear highlight when user makes a selection
    }),
  selectPart: (part) =>
    set({
      selectedPart: part,
    }),
  selectDate: (date) =>
    set({
      selectedDate: date,
    }),
  clearBrand: () =>
    set({
      selectedBrandId: undefined,
      selectedModelId: undefined,
      selectedFuelType: undefined,
      selectedPart: undefined,
      highlightTrigger: false,
    }),
  clearModel: () =>
    set({
      selectedModelId: undefined,
      selectedFuelType: undefined,
    }),
  resetSelection: () =>
    set({
      selectedBrandId: undefined,
      selectedModelId: undefined,
      selectedFuelType: undefined,
      selectedPart: undefined,
      selectedDate: undefined,
      highlightTrigger: false,
    }),
  isCarSelected: () => {
    const state = get();
    return !!(state.selectedBrandId && state.selectedModelId && state.selectedFuelType);
  },
  triggerHighlight: () =>
    set({
      highlightTrigger: true,
    }),
  clearHighlight: () =>
    set({
      highlightTrigger: false,
    }),
}));

export type CarSelectionStore = ReturnType<typeof useCarSelectionStore>;


